parameters:
- name: repo
  displayName: The repository to take the task code from
  default: microsoft/google-play-vsts-extension
- name: branch
  displayName: The branch to take the task code from
  default: users/DaniilShmelev/GooglePlayReleaseV4-test2
- name: task
  displayName: The task to build and upload
  default: GooglePlayReleaseV4
- name: collection
  displayName: URL of the collection the task will be uploaded to
  default: https://abtttestorg.visualstudio.com/DefaultCollection

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
  - repository: targetRepo
    type: github
    endpoint: DaniilShmelev
    name: microsoft/google-play-vsts-extension

steps:
- checkout: self
- checkout: targetRepo
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
- bash: |
    sudo npm i -g tfx-cli
    tfx login --service-url ${{ parameters.collection }} --token $(PAT)

    cd $(Build.SourcesDirectory)/`basename ${{ parameters.repo }}`
    git checkout ${{ parameters.branch }}
    npm i
    node make.js build --task ${{ parameters.task }}
    tfx build tasks upload --task-path _build/Tasks/${{ parameters.task }}
